apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-devops-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-devops
  template:
    metadata:
      labels:
        app: flask-devops
    spec:
      containers:
      - name: flask-devops
        image: flask-devops:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
